# Generated by Django 3.2.10 on 2022-02-24 13:35

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='category_name'),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title'),
        ),
        migrations.AddField(
            model_name='tags',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='tag_name'),
        ),
    ]
