# Generated by Django 3.2.10 on 2022-02-24 23:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='this_one', editable=False, populate_from='category_name'),
        ),
    ]
