# Generated by Django 3.2.4 on 2021-10-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211001_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='avi',
            field=models.CharField(default='https://images.unsplash.com/photo-1457449940276-e8deed18bfff?ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8cHJvZmlsZXxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60', max_length=400),
        ),
    ]
