# Generated by Django 3.2.10 on 2022-02-24 23:18

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_categories_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='this_tag', editable=False, populate_from='tag_name'),
        ),
    ]
