# Generated by Django 3.2.10 on 2022-02-24 23:20

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_tags_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='okayys', editable=False, populate_from='title'),
        ),
    ]
