# Generated by Django 3.2.4 on 2021-10-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_aboutus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='sing_up_date',
            new_name='sign_up_date',
        ),
    ]
